import express from "express";
import * as Controller from "../controllers/index.js";
import {adminRoute, authenticate} from "../middleware/auth.js";
const admin = express.Router();

// admin.post("/login", Controller.Admin.signin);
// admin.post("/forgot-password", Controller.Admin.forgotPassword);
// admin.patch("/verify-forgot-password-otp",Controller.Admin.verifyForgotOTP)
// admin.patch("/otp", Controller.Admin.verifyOTP);
// admin.post("/reset-password",Controller.Admin.resetPassword);
// admin.patch("/resend-otp",Controller.Admin.resendOtp);
// admin.patch("/resend-forgot-otp",Controller.Admin.resendForgotOtp);
// admin.post("/change-password",authenticate,adminRoute, Controller.Admin.changePassword);
// admin.get("/get-user-profile",authenticate,Controller.Admin.getProfile);
// admin.get("/get-user-list",authenticate,adminRoute,Controller.Admin.getUserList);
// admin.patch("/block-unblock-user",authenticate,adminRoute,Controller.Admin.blockOrUnblockUser);
// admin.get("/get-user",authenticate,adminRoute,Controller.Admin.getUserProfile);
// admin.get("/get-posts",authenticate,adminRoute,Controller.Admin.getPosts);
// admin.get("/get-comments",authenticate,adminRoute,Controller.Admin.getComments);
// admin.get("/get-groups",authenticate,adminRoute,Controller.Admin.getGroups);
// admin.get("/get-projects",authenticate,adminRoute,Controller.Admin.getProjects);
// admin.put("/update-profile",authenticate,adminRoute,Controller.Admin.updateProfle);
// admin.get("/get-reports",authenticate,adminRoute,Controller.Admin.getReports);
// admin.patch("/delete-post",authenticate,adminRoute,Controller.Admin.deletePost);
// admin.patch("/delete-comment",authenticate,adminRoute,Controller.Admin.deleteComment);
// admin.patch("/delete-group",authenticate,adminRoute,Controller.Admin.deleteGroup);
// admin.patch("/delete-project",authenticate,adminRoute,Controller.Admin.deleteProject);
// admin.post("/create-role",authenticate,adminRoute,Controller.Admin.createRole);
// admin.get("/get-role",authenticate,adminRoute,Controller.Admin.getRole);
// admin.put("/update-role",authenticate,adminRoute,Controller.Admin.updateRole);
// admin.delete("/delete-role",authenticate,adminRoute,Controller.Admin.deleteRole);
// admin.post("/add-user",authenticate,adminRoute,Controller.Admin.addOrgUser);
// admin.get("/get-org-user-list",authenticate,adminRoute,Controller.Admin.getUserList);
// admin.post("/update-org-user",authenticate,adminRoute,Controller.Admin.updateOrgUser);
// admin.patch("/block-unblock-org-user",authenticate,adminRoute,Controller.Admin.blockOrUnblockUser);
// admin.get("/get-privacy",authenticate,adminRoute,Controller.Admin.getPrivacy);
// admin.get("/get-terms",authenticate,adminRoute,Controller.Admin.getTerms);
// admin.put("/update-privacy",authenticate,adminRoute,Controller.Admin.updatePrivacy);
// admin.put("/update-terms",authenticate,adminRoute,Controller.Admin.updateTerms);
// admin.get("/dashboard",authenticate,adminRoute,Controller.Admin.dashboard);
// admin.get("/get-chats",authenticate,adminRoute,Controller.Admin.getChats);
// admin.post("/add-role-module",authenticate,adminRoute,Controller.Admin.addRoleModule);
// admin.post("/add-post",authenticate,adminRoute,Controller.Admin.createPost);
// admin.post("/add-faq-cat",authenticate,adminRoute,Controller.Admin.createFaqCat);
// admin.patch("/edit-faq-cat",authenticate,adminRoute,Controller.Admin.updateFaqCat);
// admin.patch("/edit-faq-cat-order",authenticate,adminRoute,Controller.Admin.updateFaqCatOrder);
// admin.get("/get-faq-cat",authenticate,adminRoute,Controller.Admin.getFaqCat);
// admin.patch("/delete-faq-cat",authenticate,adminRoute,Controller.Admin.deleteFaqCat);
// admin.post("/add-faq",authenticate,adminRoute,Controller.Admin.createFaq);
// admin.patch("/edit-faq",authenticate,adminRoute,Controller.Admin.updateFaq);
// admin.patch("/edit-faq-order",authenticate,adminRoute,Controller.Admin.updateFaqOrder);
// admin.get("/get-faq",authenticate,adminRoute,Controller.Admin.getFaq);
// admin.patch("/delete-faq",authenticate,adminRoute,Controller.Admin.deleteFaq);
// admin.post("/add-resource-cat",authenticate,adminRoute,Controller.Admin.createResourceCat);
// admin.patch("/edit-resource-cat",authenticate,adminRoute,Controller.Admin.updateResourceCat);
// admin.patch("/edit-resource-cat-order",authenticate,adminRoute,Controller.Admin.updateResourceCatOrder);
// admin.get("/get-resource-cat",authenticate,adminRoute,Controller.Admin.getResourceCat);
// admin.patch("/delete-resource-cat",authenticate,adminRoute,Controller.Admin.deleteResourceCat);
// admin.post("/add-resource",authenticate,adminRoute,Controller.Admin.createResource);
// admin.patch("/edit-resource",authenticate,adminRoute,Controller.Admin.updateResource);
// admin.patch("/edit-resource-order",authenticate,adminRoute,Controller.Admin.updateResourceOrder);
// admin.get("/get-resource",authenticate,adminRoute,Controller.Admin.getResource);
// admin.patch("/delete-resource",authenticate,adminRoute,Controller.Admin.deleteResource);
// admin.post("/add-school",authenticate,adminRoute,Controller.Admin.createSchool);
// admin.put("/edit-school",authenticate,adminRoute,Controller.Admin.updateSchool);
// admin.get("/get-school",authenticate,adminRoute,Controller.Admin.getSchools);
// admin.delete("/delete-school",authenticate,adminRoute,Controller.Admin.deleteSchool);
// admin.put("update-user",authenticate,adminRoute)


export default admin;